### ISSUE TITLE
Closing only within active window

### ISSUE THREAD

**Issue by Draghmar** [ddbln/CloseAllNoConfirm#1]
Hi.
Is there a way to set it up so it would close files only for active window? I often have few projects opened and don't want to close all files in all of them but only in the one that the window is focused on.

**Comment by ddbln** [comment]
Hey @Draghmar,

Thanks for the suggestion, great Idea! I will add it soon.

**Comment by ddbln** [comment]
Hi @Draghmar,

I've updated the Close All without Confirmation plugin to now give you the option to close all files in either the current window or in all windows. This feature will be available if the "ask_before_closing" setting is enabled, which it is by default.

You will need to upgrade the plugin to version 1.4.0 to get this feature. This should happen automatically if your Sublime Text is set to auto-update plugins. If not, you can manually upgrade by typing "Package Control: Upgrade Package" into your Command Palette.

Please feel free to share any feedback or further feature requests you may have.
